import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { ConnectButton } from '@rainbow-me/rainbowkit';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    <a href="https://docs.particle.network/auth-service/sdks/web#evm-rainbowkit-integration">
                        Particle Auth With RainbowKit
                    </a>
                </h1>
                <div className={styles.connect}>
                    <ConnectButton />
                </div>
            </main>
        </div>
    );
}
